name: something
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello world"
      - name: Print Bye
        run: eco "Bye fucker"
